### ISSUE TITLE
Namespace the static files (please)

### ISSUE THREAD

**Issue by volksman** [ppetrid/yawd-admin#16]
I think it would be a really good idea to namespace the static files since you modify bootstrap.min.js and I may want a different version for my front end.  Something like {{ STATIC_URL }}yawd/js/bootstrap.min.js

As it stands now if I call in js/bootstrap.min.js I get yours.  If I override it I loose the admin skin.

**Comment by ghost** [comment]
Yes, I know this needs to be done, we face the same problem in a new project of ours. We didn't come across the problem at an earlier stage, because yawd-admin is actually the front-end site in our main project. I will fix this, it might take a couple of days though - I need to make sure everything works as expected.

**Comment by volksman** [comment]
You could just cheat and call it something else...yawd-bootstrap.min.js  :)

**Comment by ppetrid** [comment]
I moved static files under a 'yawd-admin' directory and it seems to be ok. This could potentially break custom templates/overrides, so everyone should double-check their static file links.

**Comment by ghost** [comment]
I think that's ok now, let's close it and see if anyone objects:)
